"""Force detect announcement model

Revision ID: 063adf4ca862
Revises: 
Create Date: 2025-06-19 19:00:04.395059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063adf4ca862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('dummy', sa.String(length=10), nullable=True))
       pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('dummy')

    # ### end Alembic commands ###
