"""Add Notification model

Revision ID: 3c4e53f6db90
Revises: 063adf4ca862
Create Date: 2025-06-20 12:38:12.640846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4e53f6db90'
down_revision = '063adf4ca862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
     pass 
     

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
