"""add complaint model

Revision ID: 466da0e2ed8a
Revises: 
Create Date: 2025-06-15 13:05:58.777382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466da0e2ed8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('proof_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_complaint_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('reporter_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_email', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_complaint_user', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('quality_score')
        batch_op.drop_column('proof_filename')
        batch_op.drop_column('details')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
