"""Force Alembic to detect ContainerItem

Revision ID: 542eac1fb23f
Revises: 3c4e53f6db90
Create Date: 2025-06-20 16:19:33.644313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542eac1fb23f'
down_revision = '3c4e53f6db90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_item', schema=None) as batch_op:
        batch_op.drop_column('dummy')

    # ### end Alembic commands ###
