"""initial schema with NotificationRead

Revision ID: 7eb0dc8b6600
Revises: 
Create Date: 2025-06-22 22:17:48.123566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb0dc8b6600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_read')
    op.drop_table('thank_you_message')
    op.drop_table('photo')
    op.drop_table('ownership_event')
    op.drop_table('complaint')
    with op.batch_alter_table('claim_request', schema=None) as batch_op:
        batch_op.drop_index('ix_claim_req_user_email')
        batch_op.drop_index('ix_claim_req_report_created')

    op.drop_table('claim_request')
    op.drop_table('user')
    op.drop_table('report')
    op.drop_table('lost_item')
    op.drop_table('announcement')
    # ### end Alembic commands ###
