"""Force Alembic to detect ClaimedContainerItem

Revision ID: 96aef5e01bbc
Revises: 542eac1fb23f
Create Date: 2025-06-20 17:26:29.496326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96aef5e01bbc'
down_revision = '542eac1fb23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_item', schema=None) as batch_op:
        batch_op.drop_column('dummy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
